### ISSUE TITLE
Faithful Mods

### ISSUE THREAD

**Issue by kraineff** [F32Organization/Faithful32-1.10.2#14]
Guys in my https://minecraft.curseforge.com/projects/faithful-mods i create texture yourself, and if you take texture from there please credit me in comment of commit, like a "Some of this textures was taken from Faithful Mods by xMrVizzy"

**Comment by kraineff** [comment]
And @StefanTT I checked your textures, good work, continue in the same way

**Comment by StefanTT** [comment]
Thank you. 

I will credit next time I take anything. Up to now I make new ones or take those from 1.7.10.
Git history can be rewritten to add the credits. Unfortunately I lack the rights here to do so.

**Comment by kraineff** [comment]
I create this Issue because I seen @Artemmr commit.

**Comment by StefanTT** [comment]
(I did not think that you mean me in the first place, but I noticed that I have not credited you in the commit too.)

**Comment by smenes** [comment]
@StefanTT you have more rights now. I think ...

**Comment by StefanTT** [comment]
Yes, looks like. Thank you!  :-)

**Comment by darthvader45** [comment]
Turns out the site f32.me is down, and the resource pack from Curse doesn't seem to work right.  It still looks like the vanilla textures.

**Comment by StefanTT** [comment]
@darthvader45 this is another issue, please start a new issue next time.
However, f32.me is up again.
