### ISSUE TITLE
The top face of RFTools blocks is using the old RFTools Textures

### ISSUE THREAD

**Issue by Xiaminou** [F32Organization/Faithful32-1.10.2#15]
see for yourselves:

![2017-01-17_20 12 18](https://cloud.githubusercontent.com/assets/8670392/22468433/873eb64a-e7c8-11e6-9af6-d24a7481bc71.png)

**Comment by StefanTT** [comment]
You are right, thank you for reporting!

**Comment by Xiaminou** [comment]
Hmm the colors don't look right:

![2017-02-01_19 05 41](https://cloud.githubusercontent.com/assets/8670392/22519693/a0d8d678-e8b1-11e6-9474-e1ffa44ea35d.png)
![2017-02-01_19 06 08](https://cloud.githubusercontent.com/assets/8670392/22519694/a0ed1d68-e8b1-11e6-9171-d88c5a9a9f18.png)

**Comment by StefanTT** [comment]
Yes, looks like the texture needs to be redone completely. I only fixed the blue border yesterday.

**Comment by StefanTT** [comment]
Sorry for the delay I am currently quite busy outside of Minecraft.

**Comment by StefanTT** [comment]
@Xiaminou is the issue now fixed for you?

**Comment by Xiaminou** [comment]
Yes
