### ISSUE TITLE
Botania Mana Pools are missing textures

### ISSUE THREAD

**Issue by ghost** [F32Organization/Faithful32-1.10.2#18]
![image](https://cloud.githubusercontent.com/assets/10087813/23033624/854a47c6-f481-11e6-8d0e-1bd9750998ef.png)

Using the 2/16 2017 build

**Comment by StefanTT** [comment]
The most interesting fact is that F32 does not yet contain Botania in 1.10.2

Could it be that you changed texture packs in this play session? This happens to me sometimes when I change texture packs, but a restart of Minecraft has always fixed it.

**Comment by ghost** [comment]
I haven't changed resource packs. Restarts don't fix it. All I'm using is this and a resource pack that deletes Wither and EnderDragon global sounds, on top of F32.

I just downloaded the 1.10.2 pack from f32.me and it had Botania textures too, but the pools seem to be broken.

**Comment by StefanTT** [comment]
Ok, let's check:

- Botania r1.9-339 (the one I happen to have available) has it's textures in a folder called "botania"
- The repository on Github does not have a folder "botania"
- Downloading F32-1.10.2.zip from http://f32.me: no folder "botania" there - see yourself:
![grafik](https://cloud.githubusercontent.com/assets/2863528/23078740/3be437b2-f54a-11e6-92d4-503928d7e2a2.png)

- Starting FTB Infinity Lite 1.10 to double check, using only the downloaded F32-1.10.2.zip resource pack:
![grafik](https://cloud.githubusercontent.com/assets/2863528/23078857/ac6410d4-f54a-11e6-837f-b87948f12983.png)

Sorry, no broken botania textures here.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/10087813/23079843/3f22f79e-f557-11e6-91c2-4be2576aed04.png)

For every new build of F32, I just overwrite over the old pack, so it must be from an older build?

For now I deleted the pool.png, dilutedpool.png and infinitepool.png textures from assets\botania\textures\model

**Comment by StefanTT** [comment]
In my fresh download - an hour ago, version of 17. feb - it is not there.

**Comment by ghost** [comment]
It definitely was there in the past, since I have it.

**Comment by StefanTT** [comment]
Unfortunately I cannot do more than I did, as I have no access to the server that packages the
textures. Botania was not in the repository - we would have a history then.
I think we should close the issue.

**Comment by ghost** [comment]
Yes we should - thanks for being useless :)

Posted a temporary fix in a past comment^ until you people decide to actually work on it.

**Comment by StefanTT** [comment]
Just to finalize the topic, in case somebody else stumbles across our discussion.

The problem you reported happens when you use the botania textures from 1.7.10 in 1.10.2
A (fixed) version of the botania textures will be added to the texture pack soon - I ported them today.
