### ISSUE TITLE
Add ThermalExpansion textures

### ISSUE THREAD

**Issue by Tsyklop** [F32Organization/Faithful32-1.10.2#22]
Hi. Thermal Expansion release for 1.10.2. Please add textures for him.

Thanks.

**Comment by StefanTT** [comment]
This pull request above contains the F32 textures from 1.7.10 that can be reused, renamed to what they are called in 1.10.2 now. I do not have a modpack with thermal expansion yet, @Tsyklop can you easily test the textures?

**Comment by Tsyklop** [comment]
@StefanTT yes.

**Comment by Tsyklop** [comment]
@StefanTT I checked the texture. In the new version, everything is different - the new structure of the texture folder, the textures of the machines are made differently. The new mechanisms, objects were added.

**Comment by StefanTT** [comment]
Did you test my change?  To do so you could download my version of the F32 repository as ZIP and use this as texture pack. It's the same as it is here plus the thermal expansion changes which are not yet merged here.

You can find my repository at https://github.com/StefanTT/Faithful32-1.10.2
On the right side is a green "Clone or download" button that has a "download as zip" link in the dialog that opens if you click it.

Thank you for testing!

**Comment by StefanTT** [comment]
I will close this issue now. Those textures that were easily doable are already in F32, the rest will come when we find time.
