### ISSUE TITLE
TE Machines GUIs

### ISSUE THREAD

**Issue by Xiaminou** [F32Organization/Faithful32-1.10.2#26]
![2017-03-13_19 07 09](https://cloud.githubusercontent.com/assets/8670392/23870707/9fdbf30a-0827-11e7-9697-eb4cb8521f3b.png)
![2017-03-13_19 24 04](https://cloud.githubusercontent.com/assets/8670392/23870708/9fe47ba6-0827-11e7-86ed-1b5579487ffd.png)
![2017-03-13_20 06 46](https://cloud.githubusercontent.com/assets/8670392/23870930/9aef7532-0828-11e7-903a-b33c34bfc5a9.png)

**Comment by StefanTT** [comment]
This is a fix for the 3 machines you reported. I think the others should be checked as well, but I have no time left today to do it.

**Comment by Xiaminou** [comment]
I haven't checked all of them yet but most of them are fine.
I'll do that when I have a bit more time.

**Comment by StefanTT** [comment]
@EddyHg80 will have a look tonight (we had a little diskussion in the thread of my pull request)

**Comment by Xiaminou** [comment]
Also this:

![2017-03-14_01 50 53](https://cloud.githubusercontent.com/assets/8670392/23922788/09d6b880-0904-11e7-8296-f8957c0e5a74.png)

**Comment by EddyHg80** [comment]
That texture now it's animated and needs to be redone, so I didn't put the old one in.
You'll notice that also the redstone furnace has the same "issue".

**Comment by Xiaminou** [comment]
Alright, I wasn't sure.

**Comment by mcdodge34** [comment]
FYI I'm not sure if you're aware, but with certain augments now the Pulverizer and the Induction Smelter add a slot for liquids that are needed for the augments to work, in the Induction Smelter, you can add Blazing Pyrotheum to make ore quadrupling, and in the Pulverizer, you can add Tectonic Petrotheum to achieve ore tripling. Maybe it needs to be done on the GUI side too if anyone is working on this part...

**Comment by Xiaminou** [comment]
This is fixed actually.

**Comment by mcdodge34** [comment]
Good thanks, wasn't sure cause I didn't upgrade my machines to this stage yet, but its in my plans, want to fully test what's new with this mod.
