### ISSUE TITLE
BigReactors (Extreme Reactors now) textures not working and a fix for it

### ISSUE THREAD

**Issue by mcdodge34** [F32Organization/Faithful32-1.10.2#28]
Ok, the textures for BigReactors aren't applied and I found somehow why, I lowercased all the names of the textures in the archive for this mod and it works now, so just a quick fix to do for anyone that can do it I guess, be careful that some mods want lowercase but some don't want it, like enderio if you lowercase all the texture names, it doesn't work anymore and you get default textures... A way to find out which format the textures need is to check the mod .jar file with 7zip and check how they are in the mod itself... Its how I converted most of the textures names for Thermal Expansion 1 day after the mod was released, it was a pain in the butt but now, ores, ingots, dusts and blocks have a nice texture. Just merged what you have done with mine and its now awesome...

**Comment by StefanTT** [comment]
Yeah, most mods renamed their textures.
It seems like the lowercasing slipped under my radar.

**Comment by StefanTT** [comment]
@mcdodge34 is it fixed now for you?

**Comment by mcdodge34** [comment]
I did manually change the names of them for myself, I still wait for a new update on the F32.me pack to update and test for other textures cause every time I update, I have a crap ton of them that I modify, I use a different sky and water color, another sun and different grass textures, different mob textures also, the base is still Faithful32 modded, but its not that anymore when I'm finished with it... I know I can't distribute it so I keep the modifications I made stricly for myself.

**Comment by StefanTT** [comment]
http://www.f32.me/F32-1.10.2.zip is from today

**Comment by mcdodge34** [comment]
Last modification on the files are from 4 days ago for Big Reactor, since I already have them, I'll wait for other mod support, like those tinkers construct casts that aren't correct when you cast some stuff they aren't centered in the cast anymore.

**Comment by StefanTT** [comment]
Feel free to wait. It's only that we could close the issue if you are fine with the current solution.
