### ISSUE TITLE
Tinkers' Construct patterns/casts misaligned

### ISSUE THREAD

**Issue by Wolf68k** [F32Organization/Faithful32-1.10.2#29]
The tool heads patterns and casts are not centered or other wise line up when you make the cast.
Image to explain better http://i.imgur.com/noE8kmC.png

**Comment by StefanTT** [comment]
I know. But I have not yet found what causes this behaviour. Unfortunately.

There is no texture for the cast, so it must be made from the blank cast and punching out a hole with some texture. But I have yet to find the texture that is used.

Update: I have filed a question in the Tinkers Construct Github repository, hopefully we get a tip how to fix it.

**Comment by Wolf68k** [comment]
I'm pretty sure if the cut out of the item was centered in the texture, that would fix it.

**Comment by StefanTT** [comment]
I can try this. But the F32 head.png and the original head.png are at the exact same position in the texture.... [see the head comparison](http://storage8.static.itmages.com/i/17/0323/h_1490289191_3999873_29c896be23.png)

**Comment by Wolf68k** [comment]
Oh, ok. I never looked at the original texture, not even in game.

**Comment by StefanTT** [comment]
Currently it looks like a bug in tinkers, but the discussion is ongoing so nothing is fixed by now.

**Comment by StefanTT** [comment]
It's a Tinker's Construct bug, but they do not have priority on fixing it.
I will add corrected metadata to F32 such that the heads have no offset.
This means that they will not be centered on the cast, but it also means that the bug will not occur.

**Comment by StefanTT** [comment]
@Wolf68k please have a look at the workaround the next days and tell me what you think.

**Comment by StefanTT** [comment]
Closing the issue for now, I think it is kind of fixed.
