### ISSUE TITLE
Water in creative

### ISSUE THREAD

**Issue by rocketmonkey45** [F32Organization/Faithful32-1.10.2#32]
When in creative mode, searching for "water" in the item menu causes the game to crash. This only happens in the normal Minecraft menu. searching in JEI works fine.

**Comment by StefanTT** [comment]
Which modpack do you use?
Do you have anything extra installed, e.g. Optifine?

**Comment by StefanTT** [comment]
I can reproduce the problem with FTB Beyond in a fresh world.
To be exact: it happens without Faithful32 and only the FTB Beyond modpack.
I am 100% sure it's not a texture pack problem.
