### ISSUE TITLE
CTD Agricraft generating connected textures 

### ISSUE THREAD

**Issue by midorlo** [F32Organization/Faithful32-1.10.2#33]
Happens when using the latest f32 precompile. Precompile from 2017-13-01 does not have the issue.

Stracktrace:

https://gist.github.com/netzgeist/4429aa45deb1b8f56a7151fa36686df7

**Comment by StefanTT** [comment]
I have some questions....

Which modpack do you use?
Do you have anything extra installed, e.g. Optifine?
What did you do that triggers the crash?

**Comment by midorlo** [comment]
It is a custom modpack on top of Forge 2254 and yes, we have the usual "optimizers" that may fuzz with the data as well. Here's a quick overview:

https://gist.github.com/netzgeist/6233dbc06d3ea7026b99fd8507589bd0

**Comment by StefanTT** [comment]
Looks like some work to manually install it for testing.

Can you tell what block it is that triggers the crash?
From the log it reads like Agricraft tries to render some custom wood block.

I had stability problems with Optifine in 1.10 in the past. In my case it was the tinkers construct construction table - the one that everybody knows - rendering the items that are being crafted on the table in 3D. But version D6 of optifine - the one that you use - fixed it for me.

**Comment by midorlo** [comment]
If it's not obvious from the stacktrace, I won't let you do the dirty work. I'll play around with activated mods and report again. 

So far I can state that it's not just block rendering. Scrolling through @agricraft in JEI is fine. Weirdly, there arent any agricraft blocks in my rendering area as well. You'll get about a minute of gametime, running around in your build area before the crash.

**Comment by StefanTT** [comment]
Strange.

You could test if disabling connected textures in Optifine helps. The stack trace has something to do
with connected textures.

What happened in the texture pack since 13/03:
+ extreme reactors textures added (in fact renamed and now they are used)
+ some thermal expansion stuff
+ mystical agriculture textures added

Edit: sorry you meant january, not march. I am not used to the American date format.

**Comment by StefanTT** [comment]
While searching issue #32 I used FTBBeyond to reproduce the defect.
The crash log that I get is very interesting: [crash log](https://gist.github.com/StefanTT/d67a8e5984b4f36e5a975352250e9498)

It is the very same infinityraider mod that is causing the crash. In the case of issue #32 even without Optifine or F32 active.
