### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by amirron100** [F32Organization/Faithful32-1.10.2#34]
Hello,
I've noticed that a few mods arent supported at all or that are not fully supported but should be supported:
Biomes O' Planty
Chisel
extra utilitis 2 
Iron chest
I'm hoping that you'll update them shortly.
Thanks

**Comment by StefanTT** [comment]
The nice thing with free software is that nobody pays you for doing it and everybody who wants can participate. At the moment I am doing most work, and my time is limited.

Most mods do have incomplete support yet. More textures will be added as time goes by, but there is no guaranteed delivery date.
