### ISSUE TITLE
RFTools Endergenic Generator floating pearl has a white border.

### ISSUE THREAD

**Issue by Mizuna737** [F32Organization/Faithful32-1.10.2#39]
What it says on the tin, the floating pearl in the center of the endergenic generator has an obnoxious white square around it.

**Comment by StefanTT** [comment]
RFTools uses the vanilla minecraft ender pearl for rendering. I tried some things with the ender pearl texture, but nothing fixed it.

I opened [an issue](https://github.com/McJty/RFTools/issues/1141) at RFTools, hopefully we can fix this soon.

**Comment by StefanTT** [comment]
Found the problem ... the commit fixes the issue - at least on my computer.
@Mizuna737 could you please be so kind and test in the next days if it fixes the issue for you too?

**Comment by Mizuna737** [comment]
Sure thing, I'll test it tomorrow morning. As a temporary fix, I deleted the floatingpearl.png from assets/rftools/entities then rezipped the files.
