### ISSUE TITLE
Refined Storage minor issue 

### ISSUE THREAD

**Issue by guestds** [F32Organization/Faithful32-1.10.2#41]
issue: 2nd row of drive slots on the RS [disk drive](https://github.com/F32Organization/Faithful32-1.10.2/blob/master/assets/refinedstorage/textures/blocks/disk_drive.png) is 3 pixels instead of 4 

if youd like as im gonna fix this for myself for my mega pack (i shoved as many faithful packs into one) i can submit the texture here but if you have time its faster yourself as im lazy and dont check stuff much lol 

and yes ive checked its errored here too (cause its only possible that its from here its not known due to having so many shoved into it lol)

**Comment by StefanTT** [comment]
I hope this fixes the issue.

**Comment by StefanTT** [comment]
I close the issue now as I think it is fixed.
@guestds please comment to the issue if it is not fixed for you.
