### ISSUE TITLE
Files in wrong directory

### ISSUE THREAD

**Issue by Intipablo** [F32Organization/Faithful32-1.10.2#53]
I recently submitted a lot of Actually Additions tools, and for some reason, they have been put into the main starting directory. However they should be in actuallyadditions/textures/items/

**Comment by StefanTT** [comment]
Then fix it, please.

**Comment by Intipablo** [comment]
Oh sorry, I'm very new to Github and not quite sure how to do this.

**Comment by StefanTT** [comment]
Fixed with commit #54, also removed the files from the TODOs.
Please double check next time and please also cleanup the TODOs yourself.

**Comment by Intipablo** [comment]
Thank you, I'm very sorry for this. This won't happen again.

**Comment by StefanTT** [comment]
It's ok. I also did not review your change good enough, obviously.
