### ISSUE TITLE
1.12 Branch?

### ISSUE THREAD

**Issue by Intipablo** [F32Organization/Faithful32-1.10.2#56]
Why isn't there a 1.12 branch? I'd like to make textures for some mods that are exclusively 1.12

**Comment by StefanTT** [comment]
I do not have permissions and the F32Organization is currently quite abandoned it seems.
But if you edit the pack.mcmeta file inside the zip and change pack_format to 3 then you get all the textures that did not change since 1.10.2

**Comment by Intipablo** [comment]
Yes I know I can do that, but am I allowed to make my own 1.12.2 Repository and take textures from here?

**Comment by StefanTT** [comment]
For your personal use of course. But I fear you / we cannot redistribute the work as this repository contains no license and therefore you would need to ask everybody who's work you want to use before doing it.

**Comment by Triviuhh** [comment]
So would I just edit that pack.mcmeta file in the 1.10.2 pack and just drop it into my resource folder, or is there a process of moving over textures?
    On Friday, February 2, 2018, 10:46:15 PM PST, Stefan Taferner <notifications@github.com> wrote:  
 
 
For your personal use of course. But I fear you / we cannot redistribute the work as this repository contains no license and therefore you would need to ask everybody who's work you want to use before doing it.

**Comment by Intipablo** [comment]
Some textures might not work Triviuhh as mods might have changed the textures names. But for the most part, it is that simple correct. If you want to see what names textures have from a mod, open the mods .jar file with a program like 7zip and navigate to the texture files.

It's unfortunate that this can only be for my personal use, It would be great to make a new 1.12.2 repository that everyone could share and featured all the textures made for the version.

**Comment by StefanTT** [comment]
@Triviuhh you directly change the pack.mcmeta file in the f32 ZIP file.
@Intipablo I will migrate my work to FaithfulTeam/ModdedFaithful.
