### ISSUE TITLE
Tinkers' Construct Arrows

### ISSUE THREAD

**Issue by Xiaminou** [F32Organization/Faithful32-1.10.2#9]
The Arrow Shaft is angled the wrong way.
![2016-12-06_23 50 39](https://cloud.githubusercontent.com/assets/8670392/20947325/f0ce1bc2-bc0e-11e6-950b-13f7223cc807.png)

**Comment by shadow306k** [comment]
You only need to rotate shaft.png in assets/tconstruct/textures/items/arrow 90 degrees clockwise, and it's fine :)
Here it is rotated.
![shaft](https://cloud.githubusercontent.com/assets/20017282/21550727/16ca5e84-cdf4-11e6-9a7e-38f20c837758.png)

**Comment by StefanTT** [comment]
This was probably my fault. It will be fixed in my next pull request.

**Comment by StefanTT** [comment]
My fix is merged, please have a look if it fixes the problem for you (it should).
If you are happy with the fix then please close this issue - I do not have the permissions to close it

**Comment by shadow306k** [comment]
![9b3fb80d4f735a2162b2e1d319fa38a9](https://cloud.githubusercontent.com/assets/20017282/21965571/a95bb4dc-db5a-11e6-9647-809e2aa5cf52.png)

Yeah it works, just needs closing.

**Comment by StefanTT** [comment]
Great, thanks for testing!

**Comment by Xiaminou** [comment]
Is anyone else having issues with glass connected textures with optifine? I don't know if it's the resources pack but mine aren't connecting anymore.

**Comment by StefanTT** [comment]
Which glass in special?

(we can discuss this here, but please open a new issue next time as it is unrelated to the original issue)

**Comment by Xiaminou** [comment]
I haven't opened a ticket yet because I don't know if it's related. Vanilla glass.

**Comment by StefanTT** [comment]
Ok, no problem.

I can confirm your issue, with vanilla mincraft glass panes.
Tested with OptiFine_1.10.2_HD_U_D6

What is interesting:
* optifine and vanilla textures: connected glass panes
* optifine and f32 textures: no connected glass
* without optifine: never connected glass

I had a look at the textures, there is no obvious difference between the vanilla glass pane textures and those of F32. And as there are no connected textures at all without Optifine it is a 75% chance that it's an optifine issue.

I will do some more testing.

_update_

Unfortunately I have no idea what it could be besides an Optifine problem. Changing the connected-textures setting in Optifine also does not help.

**Comment by Xiaminou** [comment]
https://github.com/F32Organization/Faithful32-1.10.2/issues/12

It was working at first but after one of the updates it stopped working. So something you guys updated broke it.

**Comment by StefanTT** [comment]
Ok let's discuss it in #12

Please close this issue if the arrows are fixed for you.
